### ISSUE TITLE
How do you force delete a folder that is not empty?

### ISSUE THREAD

**Issue by jbwyatt4** [attachmentsme/ruby-box#115]
Hello,

I get a "Cannot delete - folder not empty error".

I want to know if there is a way to force delete a folder for convenience. I've checked the README.md, it didn't even have information on deleting a folder. Code sample would be appreciated.

**Comment by cburnette** [comment]
Hi, you might want to check out the new official Box Ruby SDK:

https://github.com/cburnette/boxr https://github.com/cburnette/boxr

You’ll see how to delete a non-empty folder in the README

thanks,
Chad

**Comment by jbwyatt4** [comment]
Thankyou for the info, but if that is new official SDK why isn't there a note in the Readme of this SDK?

Edit: i'm a new user to Box and i've already written quite of code against this SDK. That information would have been very helpful if it was in the Readme.

**Comment by cburnette** [comment]
Good point.  I need to add that to the readme.  Here is the link to the list of all official Box SDKs:

https://developers.box.com/sdks/ https://developers.box.com/sdks/

Chad
