### ISSUE TITLE
Invalid argument when installing gem on Windows

### ISSUE THREAD

**Issue by fluidvoice** [attachmentsme/ruby-box#34]
excuse my ignorance as I'm new to Ruby and box but when I attempt to install this gem I get an error. What is the problem?  thanks. 

C:>gem install ruby-box
Fetching: httpauth-0.2.0.gem (100%)
Successfully installed httpauth-0.2.0
Fetching: multi_xml-0.5.3.gem (100%)
Successfully installed multi_xml-0.5.3
Fetching: oauth2-0.9.1.gem (100%)
Successfully installed oauth2-0.9.1
Fetching: ruby-box-1.2.0.gem (100%)
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ruby-box-1.2.0/spec/fixtures/i☺ e?↨f§↓.jpg

**Comment by bcoe** [comment]
I'll test this out on Windows, and see if I can figure out a fix. In the meantime, you might be able to:

``` bash
git clone git://github.com/attachmentsme/ruby-box.git
cd ruby-box
gem build ruby-box.gemspec
gem install ruby-box-1.x.x.gem
```

I don't do much development on Windows anymore, personally, so if a fix jumps out at you during this process -- I'd greatly appreciate it if you submitted a patch :)

**Comment by fluidvoice** [comment]
Thanks Ben. I'll give it a try. No promises. I'm new to all this, including Git!

**Comment by fluidvoice** [comment]
I get the same error when performing those steps.  What is this .jpg file it's complaining about and why is the file name encoded in multibyte characters?  can this file be removed or renamed?

**Comment by bcoe** [comment]
I've published version 1.2.1 of the Gem, which removes the UTF-8 file which was giving you issues.

Please let me know if this fixes your problems.

**Comment by fluidvoice** [comment]
I was including your module/code but will switch to the gem if it works.
 thanks!

**Comment by bcoe** [comment]
Let me know if you continue to have any issues, I'm going to close this issue for the time being.
