### ISSUE TITLE
How to logon without redirect_uri

### ISSUE THREAD

**Issue by emmtte** [attachmentsme/ruby-box#36]
Hello there!

I would like to know how to log on without the "redirect_uri" and get the token. It's for a command line application.

Thanks for all.

**Comment by bcoe** [comment]
Hey the easiest way to do this is probably the following:
- Create a new Box application from your developer admin console.
- Setup the redirect_uri for your application to be localhost:
  - https://localhost/oauth2callback
- Run the RubyBox library from command line:
  - Generate the authorize_url.
  - Paste the authorize_url into the browser.
  - Copy the 'code' parameter in the browser.
  - Exchange the 'code' for an access_token from the command line.
  - Store the refresh_token somewhere, you will need to exchange this for a new access_token periodically.

At this point you can use your client credentials, the access token, and the refresh token to interact with the Box V2.0 API.
