### ISSUE TITLE
Docs on refresh token usage could be clearer

### ISSUE THREAD

**Issue by michaelmaag** [attachmentsme/ruby-box#40]
It would be helpful to indicate in the docs that, when you're using the refresh token, you should construct the session with the original access token. 

e.g. 

``` ruby
require 'ruby-box'

session = RubyBox::Session.new({
  client_id: 'your-client-id',
  client_secret: 'your-client-secret'
})

session.refresh_token('your-refresh-token')
```

will not work while the following will

``` ruby
require 'ruby-box'

session = RubyBox::Session.new({
  client_id: 'your-client-id',
  client_secret: 'your-client-secret',
  access_token: 'original-access-token'
})

session.refresh_token('your-refresh-token')
```

**Comment by bcoe** [comment]
Hey @michaelmaag It's great to get feedback, I'd encourage you to submit pull requests for any documentation changes that you'd like to see -- it's good to have another set of eyes on the documentation.
