### ISSUE TITLE
There is no way to access the http response code from RubyBox::ServerError

### ISSUE THREAD

**Issue by brendandoxo** [attachmentsme/ruby-box#57]
When uploading a file, if it fails because the account is full, a 507 response is returned.  However all I can see is RubyBox::ServerError.  I don't know if it was some other 5xx error or not.  It would be good if the entire response was included in the exception so that consumers of the gem can inspect the response for things the gem hasn't done.

**Comment by bcoe** [comment]
I've added the response body, and HTTP status code as attributes on the base RubyBoxError class. Does this do the trick for you?

https://github.com/attachmentsme/ruby-box/commit/70f105483db47d9911a7c5d0ec9b0c56b24c4ada

**Comment by brendandoxo** [comment]
that looks great!  I will try it out today.  Thanks for looking at this so quickly.

**Comment by brendandoxo** [comment]
I just tried the fix and it works great, thank you

**Comment by bcoe** [comment]
:thumbsup:
