### ISSUE TITLE
Slow when navigating folder structure

### ISSUE THREAD

**Issue by ajporterfield** [attachmentsme/ruby-box#62]
I've integrated this gem into my Rails 3 app and am experiencing a significant delay when pulling files/folders.  Here's a specific example.

I'm populating a select box with a nested folder structure from Box.  There are a total of 6 folders in my Box account - 3 top/root level and the other 3 are subfolders (see structure below).  The ajax request which populates this select box takes 25-30 second to complete!  Do you have any thoughts or suggestions?  The performance issue isn't isolated just to this method.  It's anytime I fetch and iterate over files or folders.

/
/Folder 1
/Folder 1/Nested folder 1-1
/Folder 1/Nested folder 1-2
/Folder 2
/Folder 3
/Folder 3/Nested folder 3-1

Here's the recursive method I'm using.

```
def folders_from_box(parent_folder_path = '/', recursive = true)
  folders = []

  if parent_folder_object = client.folder(parent_folder_path)
    folder_objects = parent_folder_object.folders
    if folder_objects.length > 0
      parent_folder_path += "/" unless parent_folder_path[-1] == "/"
      folder_objects.each do |folder_object|
        folder_path = parent_folder_path + folder_object.name
        folders << { id: folder_object.id, path: folder_path }
        folders += folders_from_box(folder_path) if recursive
      end
    end
  end

  return folders
end
```

**Comment by bcoe** [comment]
@ajporterfield I've always found API calls somewhat slow, especially if you're iterating multiple folders deep -- as this requires multiple API calls.

At attachments.me, to mitigate these problems, we built client-side caching strategies into our folder selecting widgets. Users would usually be interacting with a prior cache of the Box listing, and we'd update the listing with any diffs when the new API call returned. Some thoughts:
- try to use client-side caching.
- if possible, only show a top-level folder, and iterate deeper as files are needed.

Unfortunately, I think it's the nesting that's killing you -- this would result in quite a few API calls.
